[profile.default]
auto_detect_solc = false
src = 'contracts'
out = 'out'
test = 'test'
libs = ["node_modules", "lib"]
script = 'scripts'
cache_path = 'cache-forge'
gas_reports = ["*"]
optimizer_runs = 100
fs_permissions = [
  { access = "read", path = "./node_modules/@merkl/registry/dist/src/registry.json" }, 
  { access = "write", path = "./transactions" }, 
]
solc = "0.8.25"

ffi = true

[profile.deploy]
auto_detect_solc = false
src = 'contracts'
out = 'out'
test = 'test'
libs = ["node_modules"]
script = 'scripts'
cache_path = 'cache-forge'
gas_reports = ["*"]
optimizer_runs = 100
fs_permissions = [
  { access = "read", path = "./node_modules/@merkl/registry/dist/src/registry.json" }, 
  { access = "write", path = "./transaction.json" }, 
  { access = "write", path = "./transactions.json" }
]
solc = "0.8.25"

[fuzz]
runs = 500

[invariant]
runs = 500

[profile.dev]
via_ir = false

[rpc_endpoints]
localhost = "${LOCALHOST_NODE_URI}"
mainnet = "${ETH_NODE_URI_1}"
polygon = "${ETH_NODE_URI_137}"
fantom = "${ETH_NODE_URI_250}"
optimism = "${ETH_NODE_URI_10}"
arbitrum = "${ETH_NODE_URI_42161}"
avalanche = "${ETH_NODE_URI_43114}"
bsc = "${ETH_NODE_URI_56}"
gnosis = "${ETH_NODE_URI_100}"
polygonzkevm = "${ETH_NODE_URI_1101}"
base = "${ETH_NODE_URI_8453}"
bob = "${ETH_NODE_URI_60808}"
linea = "${ETH_NODE_URI_59144}"
zksync = "${ETH_NODE_URI_324}"
mantle = "${ETH_NODE_URI_5000}"
blast = "${ETH_NODE_URI_81457}"
mode = "${ETH_NODE_URI_34443}"
thundercore = "${ETH_NODE_URI_108}"
coredao = "${ETH_NODE_URI_1116}"
xlayer = "${ETH_NODE_URI_196}"
taiko = "${ETH_NODE_URI_167000}"
fuse = "${ETH_NODE_URI_122}"
immutable = "${ETH_NODE_URI_13371}"
scroll = "${ETH_NODE_URI_534352}"
manta = "${ETH_NODE_URI_169}"
sei = "${ETH_NODE_URI_1329}"
celo = "${ETH_NODE_URI_42220}"
fraxtal = "${ETH_NODE_URI_252}"
astar = "${ETH_NODE_URI_592}"
rootstock = "${ETH_NODE_URI_30}"
moonbeam = "${ETH_NODE_URI_1284}"
skale = "${ETH_NODE_URI_2046399126}"
worldchain = "${ETH_NODE_URI_480}"
lisk = "${ETH_NODE_URI_1135}"
etherlink = "${ETH_NODE_URI_42793}"
swell = "${ETH_NODE_URI_1923}"
fork = "${FORK_NODE_URI}"
sonic = "${ETH_NODE_URI_146}"
corn = "${ETH_NODE_URI_21000000}"
ink = "${ETH_NODE_URI_57073}"
ronin = "${ETH_NODE_URI_2020}"
flow = "${ETH_NODE_URI_747}"
berachain = "${ETH_NODE_URI_80094}"
nibiru = "${ETH_NODE_URI_6900}"
zircuit = "${ETH_NODE_URI_48900}"
apechain = "${ETH_NODE_URI_33139}"
hyperevm = "${ETH_NODE_URI_999}"
hemi="${ETH_NODE_URI_43111}"
xdc="${ETH_NODE_URI_50}"
katana="${ETH_NODE_URI_747474}"
tac="${ETH_NODE_URI_239}"
plasma="${ETH_NODE_URI_9745}"
mezo="${ETH_NODE_URI_31612}"
redbelly="${ETH_NODE_URI_151}"
saga="${ETH_NODE_URI_5464}"
ethereal="${ETH_NODE_URI_5064014}"
monad="${ETH_NODE_URI_143}"
megaeth="${ETH_NODE_URI_4326}"
stable="${ETH_NODE_URI_988}"
plume="${ETH_NODE_URI_98866}"
unichain=${ETH_NODE_URI_130}
soneium=${ETH_NODE_URI_1868}
0g=${ETH_NODE_URI_16661}

[etherscan]
localhost = { url = "http://localhost:4000", key = "none" }
mainnet = { chainId = 1, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1}" }
polygon = { chainId = 137, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_137}" }
optimism = { chainId = 10, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_10}" }
arbitrum = { chainId = 42161, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_42161}" }
avalanche = { chainId = 43114, key = "${AVALANCHE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_43114}" }
bsc = { chainId = 56, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_56}" }
gnosis = { chainId = 100, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_100}" }
polygonzkevm = { chainId = 1101, key = "${POLYGONZKEVM_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1101}" }
base = { chainId = 8453, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_8453}" }
bob = { chainId = 60808, key = "${BOB_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_60808}" }
linea = { chainId = 59144, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_59144}" }
zksync = { chainId = 324, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_324}" }
mantle = { chainId = 5000, key = "${MANTLE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_5000}" }
blast = { chainId = 81457, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_81457}" }
mode = { chainId = 34443, key = "${MODE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_34443}" }
thundercore = { chainId = 108, key = "${THUNDERCORE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_108}" }
coredao = { chainId = 1116, key = "${COREDAO_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1116}" }
xlayer = { chainId = 196, key = "${XLAYER_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_196}" }
taiko = { chainId = 167000, key = "${TAIKO_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_167000}" }
fuse = { chainId = 122, key = "${FUSE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_122}" }
immutable = { chainId = 13371, key = "${IMMUTABLE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_13371}" }
scroll = { chainId = 534352, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_534352}" }
manta = { chainId = 169, key = "${MANTA_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_169}" }
sei = { chainId = 1329, key = "${SEI_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1329}" }
celo = { chainId = 42220, key = "${CELO_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_42220}" }
fraxtal = { chainId = 252, key = "${FRAXTAL_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_252}" }
astar = { chainId = 592, key = "${ASTAR_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_592}" }
rootstock = { chainId = 30, key = "${ROOTSTOCK_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_30}" }
moonbeam = { chainId = 1284, key = "${MOONBEAM_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1284}" }
skale = { chainId = 2046399126, key = "${SKALE_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_2046399126}" }
worldchain = { chainId = 480, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_480}" }
lisk = { chainId = 1135, key = "${LISK_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1135}" }
etherlink = { chainId = 42793, key = "${ETHERLINK_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_42793}" }
swell = { chainId = 1923, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1923}" }
sonic = { chainId = 146, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_146}" }
corn = { chainId = 21000000, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_21000000}" }
ink = { chainId = 57073, key = "${INK_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_57073}" }
ronin = { chainId = 2020, key = "${RONIN_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_2020}" }
flow = { chainId = 747, key = "${FLOW_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_747}" }
berachain = { chainId = 80094, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_80094}" }
nibiru = { chainId = 6900, key = "${NIBIRU_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_6900}" }
zircuit = { chainId = 48900, key = "${ZIRCUIT_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_48900}" }
apechain = { chainId = 33139, key = "${APECHAIN_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_33139}" }
hyperevm = { chainId = 999, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_999}" }
hemi = { chainId = 43111, key = "${HEMI_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_43111}" }
xdc = { chainId = 50, key = "${XDC_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_50}" }
katana = {chainId = 747474, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_747474}" }
tac = {chainId = 239, key = "${TAC_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_239}" }
plasma = {chainId = 9745, key = "${PLASMA_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_9745}" }
mezo = {chainId = 31612, key = "${MEZO_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_31612}" }
redbelly = {chainId = 151, key = "${REDBELLY_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_151}" } 
saga = {chainId = 5464, key = "${SAGA_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_5464}" }
ethereal = {chainId = 5064014, key = "none", url = "${VERIFIER_URL_5064014}" } 
monad = {chainId = 143, key = "${MONAD_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_143}" }
megaeth = {chainId = 4326, key = "${MEGAETH_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_4326}" }
stable = {chainId = 988, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_988}" }
plume = {chainId = 98866, key = "${PLUME_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_98866}" }
unichain = {chainId = 130, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_130}" }
soneium = {chainId = 1868, key = "${SONEIUM_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_1868}" }
0g = {chainId = 16661, key = "${0G_ETHERSCAN_API_KEY}", url = "${VERIFIER_URL_16661}" }
 
