[profile.default]
auto_detect_solc = false
src = 'contracts'
out = 'out'
test = 'test'
libs = ["node_modules", "lib"]
script = 'scripts'
cache_path = 'cache-forge'
gas_reports = ["*"]
optimizer_runs = 100
fs_permissions = [
  { access = "read", path = "./node_modules/@merkl/registry/dist/src/registry.json" }, 
  { access = "write", path = "./transactions" },
  { access = "write", path = "./deployments" },
]
solc = "0.8.25"

ffi = true

[profile.deploy]
auto_detect_solc = false
src = 'contracts'
out = 'out'
test = 'test'
libs = ["node_modules"]
script = 'scripts'
cache_path = 'cache-forge'
gas_reports = ["*"]
optimizer_runs = 100
fs_permissions = [
  { access = "read", path = "./node_modules/@merkl/registry/dist/src/registry.json" }, 
  { access = "write", path = "./transaction.json" }, 
  { access = "write", path = "./transactions.json" }
]
solc = "0.8.25"

[fuzz]
runs = 500

[invariant]
runs = 500

[profile.dev]
via_ir = false

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
mainnet = "${ETH_NODE_URI_1}"
optimism = "${ETH_NODE_URI_10}"
rootstock = "${ETH_NODE_URI_30}"
xdc="${ETH_NODE_URI_50}"
bsc = "${ETH_NODE_URI_56}"
gnosis = "${ETH_NODE_URI_100}"
fuse = "${ETH_NODE_URI_122}"
unichain= "${ETH_NODE_URI_130}"
polygon = "${ETH_NODE_URI_137}"
monad="${ETH_NODE_URI_143}"
sonic = "${ETH_NODE_URI_146}"
redbelly="${ETH_NODE_URI_151}"
manta = "${ETH_NODE_URI_169}"
xlayer = "${ETH_NODE_URI_196}"
tac="${ETH_NODE_URI_239}"
fraxtal = "${ETH_NODE_URI_252}"
zksync = "${ETH_NODE_URI_324}"
worldchain = "${ETH_NODE_URI_480}"
astar = "${ETH_NODE_URI_592}"
flow = "${ETH_NODE_URI_747}"
hyperevm = "${ETH_NODE_URI_999}"
stable="${ETH_NODE_URI_988}"
lisk = "${ETH_NODE_URI_1135}"
moonbeam = "${ETH_NODE_URI_1284}"
sei = "${ETH_NODE_URI_1329}"
soneium="${ETH_NODE_URI_1868}"
swell = "${ETH_NODE_URI_1923}"
ronin = "${ETH_NODE_URI_2020}"
citrea= "${ETH_NODE_URI_4114}"
megaeth="${ETH_NODE_URI_4326}"
mantle = "${ETH_NODE_URI_5000}"
saga="${ETH_NODE_URI_5464}"
nibiru = "${ETH_NODE_URI_6900}"
base = "${ETH_NODE_URI_8453}"
plasma="${ETH_NODE_URI_9745}"
immutable = "${ETH_NODE_URI_13371}"
0g= "${ETH_NODE_URI_16661}"
corn = "${ETH_NODE_URI_21000000}"
mezo="${ETH_NODE_URI_31612}"
apechain = "${ETH_NODE_URI_33139}"
mode = "${ETH_NODE_URI_34443}"
arbitrum = "${ETH_NODE_URI_42161}"
celo = "${ETH_NODE_URI_42220}"
etherlink = "${ETH_NODE_URI_42793}"
hemi="${ETH_NODE_URI_43111}"
avalanche = "${ETH_NODE_URI_43114}"
zircuit = "${ETH_NODE_URI_48900}"
ink = "${ETH_NODE_URI_57073}"
linea = "${ETH_NODE_URI_59144}"
bob = "${ETH_NODE_URI_60808}"
berachain = "${ETH_NODE_URI_80094}"
blast = "${ETH_NODE_URI_81457}"
plume="${ETH_NODE_URI_98866}"
taiko = "${ETH_NODE_URI_167000}"
scroll = "${ETH_NODE_URI_534352}"
katana="${ETH_NODE_URI_747474}"
skale = "${ETH_NODE_URI_2046399126}"
ethereal="${ETH_NODE_URI_5064014}"
eden="${ETH_NODE_URI_714}"
tempo="${ETH_NODE_URI_4217}"


[etherscan]
localhost = { url = "http://localhost:4000", key = "none" }
mainnet = {chainId = 1, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1" }
optimism = {chainId = 10, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=10" }
rootstock = {chainId = 30, key = "none", url = "https://rootstock.blockscout.com/api/" }
xdc = {chainId = 50, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=50" }
bsc = {chainId = 56, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=56" }
gnosis = {chainId = 100, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=100" }
fuse = {chainId = 122, key = "none", url = "https://explorer.fuse.io/api" }
unichain = {chainId = 130, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=130" }
polygon = {chainId = 137, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=137" }
monad = {chainId = 143, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=143" }
sonic = {chainId = 146, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=146" }
redbelly = {chainId = 151, key = "none", url = "https://api.routescan.io/v2/network/mainnet/evm/151/etherscan" }
manta = {chainId = 169, key = "none", url = "https://api.socialscan.io/manta/v1/explorer/command_api/contract" }
xlayer = {chainId = 196, key = "none", url = "https://www.oklink.com/api/v5/explorer/contract/verify-source-code-plugin/XLAYER" }
tac = {chainId = 239, key = "none", url = "https://explorer.tac.build/api" }
fraxtal = {chainId = 252, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=252" }
zksync = {chainId = 324, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=324" }
worldchain = {chainId = 480, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=480" }
astar = {chainId = 592, key = "none", url = "https://astar.blockscout.com/api/" }
flow = {chainId = 747, key = "none", url = "https://api.flowscan.io/api" }
stable = {chainId = 988, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=988" }
hyperevm = {chainId = 999, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=999" }
lisk = {chainId = 1135, key = "none", url = "https://blockscout.lisk.com/api/" }
moonbeam = {chainId = 1284, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1284" }
sei = {chainId = 1329, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1329" }
soneium = {chainId = 1868, key = "none", url = "https://soneium.blockscout.com/api" }
swell = {chainId = 1923, key = "none", url = "https://explorer.swellnetwork.io:443/api/" }
ronin = {chainId = 2020, key = "none", url = "https://sourcify.roninchain.com/server/" }
citrea = {chainId = 4114, key = "none", url = "https://explorer.mainnet.citrea.xyz/api" }
megaeth = {chainId = 4326, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=4326" }
mantle = {chainId = 5000, key = "none", url = "https://explorer.mantle.xyz/api/" }
saga = {chainId = 5464, key = "none", url = "https://sagaevm.sagaexplorer.io/api" }
nibiru = {chainId = 6900, key = "none", url = "https://api.routescan.io/v2/network/mainnet/evm/6900/etherscan" }
base = {chainId = 8453, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=8453" }
plasma = {chainId = 9745, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=9745" }
immutable = {chainId = 13371, key = "none", url = "https://immutable-mainnet.blockscout.com/api" }
0g = {chainId = 16661, key = "none", url = "https://chainscan-galileo.0g.ai/" }
corn = {chainId = 21000000, key = "none", url = "https://api.routescan.io/v2/network/mainnet/evm/21000000/etherscan" }
mezo = {chainId = 31612, key = "none", url = "https://explorer.mezo.org/api" }
apechain = {chainId = 33139, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=33139" }
mode = {chainId = 34443, key = "none", url = "https://api.routescan.io/v2/network/mainnet/evm/34443/etherscan" }
arbitrum = {chainId = 42161, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42161" }
celo = {chainId = 42220, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42220" }
etherlink = {chainId = 42793, key = "none", url = "https://explorer.etherlink.com/api" }
hemi = {chainId = 43111, key = "none", url = "https://explorer.hemi.xyz/api" }
avalanche = {chainId = 43114, key = "none", url = "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan" }
zircuit = {chainId = 48900, key = "none", url = "https://explorer.zircuit.com/" }
ink = {chainId = 57073, key = "none", url = "https://explorer.inkonchain.com/api" }
linea = {chainId = 59144, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=59144" }
bob = {chainId = 60808, key = "none", url = "https://explorer.gobob.xyz/api" }
berachain = {chainId = 80094, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=80094" }
blast = {chainId = 81457, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=81457" }
plume = {chainId = 98866, key = "none", url = "https://explorer.plume.org/api" }
taiko = {chainId = 167000, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=167000" }
scroll = {chainId = 534352, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=534352" }
katana = {chainId = 747474, key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=747474" }
skale = {chainId = 2046399126, key = "none", url = "https://internal-hubs.explorer.mainnet.skalenodes.com:10001/api" }
ethereal = {chainId = 5064014, key = "none", url = "https://explorer.ethereal.trade/api" }
eden = {chaindId = 714, key = "none", url = "https://eden.blockscout.com/" }
tempo = {chaindId = 4217, key = "none", url = "https://contracts.tempo.xyz" }



