name: Setup repo
description: Runs all steps to setup the repo (install node_modules, build, etc...)
inputs:
  registry-token:
    description: 'PAT to access registries'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - uses: actions/cache@v3
      id: bun-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install
      env:
        GH_REGISTRY_ACCESS_TOKEN: ${{ inputs.registry-token }}

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
