name: 'CI Deep'

on:
  schedule:
    - cron: '0 3 * * 0' # at 3:00am UTC every Sunday
  workflow_dispatch:
    inputs:
      fuzzRuns:
        default: '10000'
        description: 'Unit: number of fuzz runs.'
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          registry-token: ${{ secrets.SDK_READ_ACCESS_TOKEN }}

      - name: Run solhint
        run: bun lint

      - name: 'Add lint summary'
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          registry-token: ${{ secrets.SDK_READ_ACCESS_TOKEN }}

      - name: Compile foundry
        run: bun foundry:compile --sizes --skip scripts/utils/CreateXConstants.sol

      - name: 'Cache the build so that it can be re-used by the other jobs'
        uses: 'actions/cache/save@v3'
        with:
          key: 'build-${{ github.sha }}'
          path: |
            cache-forge
            out
            cache-hh
            artifacts
            typechain
            node_modules

      - name: 'Add build summary'
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  foundry-tests:
    needs: ['build', 'lint']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: 'Restore the cached build'
        uses: 'actions/cache/restore@v3'
        with:
          fail-on-cache-miss: true
          key: 'build-${{ github.sha }}'
          path: |
            cache-forge
            out
            cache-hh
            artifacts
            typechain
            node_modules

      - name: Run Foundry tests
        run: bun foundry:test
        env:
          ETH_NODE_URI_OPTIMISM: ${{ secrets.ETH_NODE_URI_OPTIMISM }}
          ETH_NODE_URI_ARBITRUM: ${{ secrets.ETH_NODE_URI_ARBITRUM }}
          ETH_NODE_URI_MAINNET: ${{ secrets.ETH_NODE_URI_MAINNET }}
          FOUNDRY_FUZZ_RUNS: ${{ github.event.inputs.fuzzRuns || '10000' }}

      - name: 'Add test summary'
        run: |
          echo "## Foundry Unit tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
