name: Merkl Contracts CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow_to_run:
        type: choice
        description: Which workflow to run?
        required: true
        options:
          - all
          - hardhat-tests
          - foundry-tests
  pull_request:
    types:
      - ready_for_review
      - review_requested
  pull_request_review:
    types: [submitted]

defaults:
  run:
    shell: bash

jobs:
  run-linters:
    name: Run Linters
    if: github.ref == 'refs/heads/main' || github.event.review.state == 'approved' || github.event.action == 'ready_for_review' || github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - name: Install dependencies
        run: |
          npm config set //registry.npmjs.org/
          yarn install --frozen-lockfile
      - name: Run solhint
        run: yarn solhint --fix --max-warnings 20 'contracts/**/*.sol'
      - name: Run eslint
        run: yarn eslint --ignore-path .gitignore --fix --max-warnings 30 'test/**/*.{js,ts}' '*.{js,ts}'

  hardhat-tests:
    name: Run Hardhat Tests
    if: github.ref == 'refs/heads/main' || github.event.inputs.workflow_to_run == 'all' || github.event.inputs.workflow_to_run == 'hardhat-tests' || github.event.review.state == 'approved' || github.event.action == 'ready_for_review' || github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - name: Install dependencies
        run: |
          npm config set //registry.npmjs.org/
          yarn install --frozen-lockfile

      - name: Compile
        run: yarn hardhat:compile
      - name: Run unit tests
        run: yarn hardhat:test
        env:
          ENABLE_GAS_REPORT: true
          CI: true
          ETH_NODE_URI_ARBITRUM: ${{ secrets.ETH_NODE_URI_MAINNET }}
