name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          registry-token: ${{ secrets.SDK_READ_ACCESS_TOKEN }}

      - name: Run solhint
        run: bun lint

      - name: 'Add lint summary'
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          registry-token: ${{ secrets.SDK_READ_ACCESS_TOKEN }}

      - name: Compile foundry
        run: forge build --sizes --skip scripts/utils/CreateXConstants.sol

      - name: 'Cache the build so that it can be re-used by the other jobs'
        uses: 'actions/cache/save@v3'
        with:
          key: 'build-${{ github.sha }}'
          path: |
            cache-forge
            out
            node_modules

      - name: 'Add build summary'
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  foundry-tests:
    needs: ['build', 'lint']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          registry-token: ${{ secrets.SDK_READ_ACCESS_TOKEN }}

      - name: Run Foundry tests
        run: bun foundry:test
        env:
          FOUNDRY_FUZZ_RUNS: '5000'
          ETH_NODE_URI_OPTIMISM: ${{ secrets.ETH_NODE_URI_OPTIMISM }}
          ETH_NODE_URI_ARBITRUM: ${{ secrets.ETH_NODE_URI_ARBITRUM }}
          ETH_NODE_URI_MAINNET: ${{ secrets.ETH_NODE_URI_MAINNET }}

      - name: 'Add test summary'
        run: |
          echo "## Foundry Unit tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
