name: Coverage Report
on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          registry-token: ${{ secrets.SDK_READ_ACCESS_TOKEN }}

      - name: Compile foundry
        run: forge build

      - name: 'Install lcov'
        run: 'sudo apt-get install lcov'

      - name: 'Generate the coverage report using the unit and the integration tests'
        run: 'bun ci:coverage'
        env:
          OPTIMISM_NODE_URI: ${{ secrets.ETH_NODE_URI_OPTIMISM }}
          ARBITRUM_NODE_URI: ${{ secrets.ETH_NODE_URI_ARBITRUM }}
          BASE_NODE_URI: ${{ secrets.ETH_NODE_URI_MAINNET }}

      - name: 'Upload coverage report to Codecov'
        uses: 'codecov/codecov-action@v3'
        with:
          files: './lcov.info'
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: 'Add coverage summary'
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
